spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-app
    username: Ashwani
    password: ashwani@93333
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    driver-class-name: org.postgresql.Driver
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always



